CRUD/Perpustakaan/Perpustakaan/Controllers/AnggotaController.cs
using Microsoft.AspNetCore.Mvc;
using Perpustakaan.datamodels;
using Perpustakaan.Services;
using Perpustakaan.viewmodels;

namespace med_id.Controllers
{
    public class AnggotaController : Controller
    {
        AnggotaService anggotaService;
        public AnggotaController(AnggotaService _anggotaService)
        {
            anggotaService = _anggotaService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            ViewBag.CurrentFilter = searchString;
            List<MAnggotum> data = await anggotaService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Fullname.ToLower().Contains(searchString.ToLower())).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Fullname).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Fullname).ToList();
                    break;
            }

            return View(data);
        }
        public IActionResult Create()
        {
            MAnggotum data = new MAnggotum();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MAnggotum dataParam)
        {
            // dataParam.CreatedBy = 1;
            VMResponse respon = await anggotaService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExsist(string name, int id)
        {
            bool isExist = await anggotaService.CheckName(name, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            MAnggotum data = await anggotaService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MAnggotum dataParam)
        {
            //dataParam.ModifiedBy = 1;
            VMResponse respon = await anggotaService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Detail(int id)
        {
            MAnggotum data = await anggotaService.GetDataById(id);
            return PartialView(data);
        }


        /*      [HttpGet("HapusData")]*/
        public async Task<IActionResult> Delete(int id)
        {
            MAnggotum data = await anggotaService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int modifedby)
        {
            //int modifedby = 1;
            VMResponse respon = await anggotaService.Delete(id, modifedby);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Controllers/BukuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationParts;
using Perpustakaan.datamodels;
using Perpustakaan.Services;
using Perpustakaan.viewmodels;
using System.Data;
namespace xpos334.Controllers
{
    public class BukuController : Controller
    {
        private BukuService bukuService;
        private int IdUser = 1;

        public BukuController(BukuService _bukuService)
        {
            bukuService = _bukuService;
        }

        public async Task<IActionResult>          
            Index(string sortOrder,
                  string searchString,
                  string currentFilter,
                  int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<MBuku> data = await bukuService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Judul.ToLower().Contains(searchString.ToLower())
                || a.Penerbit.ToLower().Contains(searchString.ToLower())).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Judul).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Judul).ToList();
                    break;
            }

            return View(PaginatedList<MBuku>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public IActionResult Create()
        {
            MBuku data = new MBuku();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MBuku dataParam)
        {
            dataParam.CreatedBy= IdUser;
            VMResponse respon = await bukuService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExsist(string nameCategory, int id)
        {
            bool isExist = await bukuService.CheckCategoryByName(nameCategory, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            MBuku data = await bukuService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MBuku dataParam)
        {
            dataParam.ModifiedBy = IdUser;
            VMResponse respon = await bukuService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            MBuku data = await bukuService.GetDataById(id);
            return PartialView(data);
        }

        /*      [HttpGet("HapusData")]*/
        public async Task<IActionResult> Delete(int id)
        {
            MBuku data = await bukuService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            int createBy = IdUser;
            VMResponse respon = await bukuService.Delete(id, createBy);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <!--Ini Untuk lempar juga-->
    <script src="~/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist//jquery.validate.min.js"></script>

    <!-- Custom CSS -->
    <link href="~/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/adminmart/dist/css/style.min.css" rel="stylesheet">
    <!-- Toastr -->
    <script src="~/adminmart/plugins/toastr/toastr.min.js"></script>
    <link rel="stylesheet" href="~/adminmart/plugins/toastr/toastr.min.css">
    <!-- Sweetalert2 -->
    <script src="~/adminmart/plugins/sweetalert2/sweetalert2.js"></script>
    <!-- Script PDF -->
    <script src="~/jsPDF-1.3.2/dist/jspdf.min.js"></script>


</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
@* 
        <partial name="_Header" />*@
        <partial name="_Sidebar" /> 


        <div class="page-wrapper">

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer text-center text-muted">
                All Rights Reserved by Adminmart. Designed and Developed by
                <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>

    </div>





    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal_body">
                    ...
                </div>
                @* <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
                </div> *@
            </div>
        </div>
    </div>
    <!--spinner-->
    <div class="modal fade" id="modal_load">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center" id="modal_load_body">
                    <div class="spinner-grow text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <h3>Please wait..</h3>
                </div>
            </div>
        </div>
    </div>




    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->

    <script src="~/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/adminmart/dist/js/app-style-switcher.js"></script>
    <script src="~/adminmart/dist/js/feather.min.js"></script>
    <script src="~/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/adminmart/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/adminmart/dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="~/adminmart/assets/extra-libs/c3/d3.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/c3/c3.min.js"></script>
    <script src="~/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/adminmart/dist/js/pages/dashboards/dashboard1.min.js"></script>
    <!--close-->


</body>
</html>

CRUD/Perpustakaan/Perpustakaan/Views/Shared/_Sidebar.cshtml
<aside class="left-sidebar" data-sidebarbg="skin6">

    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Home" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon" style="color:orange"></i><span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Anggota" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="user-plus" class="feather-icon" style="color:green"></i><span class="hide-menu">Anggota </span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Buku" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="user-plus" class="feather-icon" style="color:green"></i><span class="hide-menu">Buku </span>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->



</aside>